# Generated by Django 3.2.12 on 2022-02-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channeldisplay_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channeldisplay',
            old_name='title',
            new_name='channel',
        ),
    ]
