# Generated by Django 3.2.12 on 2022-02-18 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0004_auto_20220218_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Message',
        ),
    ]
